
# Connexion
security_login_form:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
   
security_login_check:
    path:     /login_check
    defaults: { _controller: AppBundle:Security:loginCheck }
   
     
security_logout:
    path:     /logout
    defaults: { _controller: AppBundle:Security:logout }
   

# reset password
reset_password_form:
    path:    /reset-password
    defaults: { _controller: AppBundle:Password:VueResetPassword }
    
reset_password_send_email:
    path:    /reset-password/send/email
    defaults: { _controller: AppBundle:Password:SendLinkReset }
   
reset_password_send_email_success:
    path:    /reset-password/{email}
    defaults: { _controller: AppBundle:Password:SendLinkSuccess }
    

reset_password_change_password_form:
    path:    /change-password/{token}
    defaults: { _controller: AppBundle:Password:ChangePasswordForm }
    

reset_password_change_password:
    path:    /change-password-success
    defaults: { _controller: AppBundle:Password:ChangePassword }
    


#inscription
register_form:
    path:     /register
    defaults: { _controller: AppBundle:Register:register }
    
register_wait:
    path:     /register/checkEmail/{email}
    defaults: { _controller: AppBundle:Register:checkEmail }
    
register_active_compte:
    path:    /login/{token}
    defaults: { _controller: AppBundle:Register:Active }


# profile
profile_view:
    path:    /profile/
    defaults: { _controller: AppBundle:Profile:view }

change_password:
    path:    /profile/change-password
    defaults: { _controller: AppBundle:ChangePassword:changepassword }
    methods: [GET|POST]
